# RUN THIS FILE ONCE TO CREATE A TEST DATABASE AND TABLES

DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;

DROP TABLE IF EXISTS mailing;
CREATE TABLE mailing (
  addr VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS count_tbl;
CREATE TABLE count_tbl(
	do_name VARCHAR(255) NOT NULL, 
	num_addr INT NOT NULL, 
	count_date DATE NOT NULL
);

# HARDCODE SOME DATA IN THE TEST DATABASE SO WE SIMULATE DATA 30 DAYS AGO FOR TESTING PURPOSES
# TEST DATA FOR BOTH TABLES CAN BE GENERATED BY RUNNING genTestData.pl and updateCount.pl
insert into count_tbl values ('casalemedia.com', 10, DATE_SUB(CURDATE(), INTERVAL 1 MONTH));
insert into count_tbl values ('gmail.com', 9, DATE_SUB(CURDATE(), INTERVAL 1 MONTH));
insert into count_tbl values ('amazon.com', 12, DATE_SUB(CURDATE(), INTERVAL 1 MONTH));
insert into count_tbl values ('hotmail.com', 8, DATE_SUB(CURDATE(), INTERVAL 1 MONTH));
insert into count_tbl values ('rogers.com', 14, DATE_SUB(CURDATE(), INTERVAL 1 MONTH));
insert into count_tbl values ('ibm.com', 17, DATE_SUB(CURDATE(), INTERVAL 1 MONTH));
insert into count_tbl values ('yahoo.com', 14, DATE_SUB(CURDATE(), INTERVAL 1 MONTH));
